config/routes.rb
Rails.application.routes.draw do

  root 'home#welcome'

  get '/intro', to: 'home#intro'

  get '/candidates', to: 'candidates#index'

  get '/candidates/:id', to: 'candidates#show'

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/login', to: 'candidates#index'
  

    resources :voters
    resources :sessions
    resources :candidates
    resources :quizzes

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :answers
  belongs_to :quiz
  validates_presence_of :prompt
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
	belongs_to :voter
end


# Add validations to ensure that a checkbox is selected, and only 1 checkbox is selected

app/models/voter.rb
class Voter < ActiveRecord::Base
	has_many :quizzes
	# validates_presence_of :email
	# validates_format_of :email, with: /regex/i
	# validates_presence_of :password
	# validates_uniqueness_of :email
	# validates_length_of :password, minimum: 3

	# has_many :answered_quizzes :class_name => "quiz", :through => :results :foreign_key => "quiz_id"
	validates :password,
          presence: true,
          length: { minimum: 5 }
	validates :email,
			uniqueness: true,
			presence: true,
			format: { with: /regex/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
  helper_method :current_voter
  def current_voter
  	@current_voter ||= Voter.find(session[:voter_id]) if session[:voter_id]
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController


#Marco Rubio, Ted Cruz, The Donald, Chris Christie, Jeb Bush, John Kasich, Ben Carson

  def index
  	@candidates = Candidate.all
  	# How do we display only Reps or only Dems? partial view?
  end

  def show
    @v = current_voter
  	@c = Candidate.find(params[:id])
  	# how do we display a candidate without doing it by id?
  end


  private 

  def candidate_params
  	params.require(:candidate).permit(:fname, :lname, :city, :state, :birthday, :party, :avatar)

  end  


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def welcome
		# landing page where voter signs up or logs in
	end

	def intro

	@voter = current_voter
	@quiz = Quiz.new


	# the intro.html.erb includes the quick definitions and issues "spine" 
	end

	def select
	# the select.html.erb is the page with two options: Rep or Dem
	end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  # before_action :find_question

  def index
  end

  def new
   # @quiz = Quiz.new(voter_id: current_voter.id)
    @quiz = Quiz.new
    @voter = current_voter
  end

  def create
    
    @quiz = Quiz.new(quiz_params)
    @quiz.voter_id = current_voter.id
    @voter = Voter.where(id:current_voter.id).last
    @voter.libVal = 0
    @voter.conVal = 0
    @voter.save
    if @quiz.save
      # @answers = [:answer1, :answer2, :answer3, :answer4, :answer5, :answer6, :answer7, :answer8, :answer9, :answer10]
      params[:quiz].fetch_values("answer1", "answer2", "answer3", "answer4", "answer5", "answer6", "answer7", "answer8", "answer9", "answer10").each do |q|
        if q == "yes"
          @voter.libVal += 10
          @voter.save
        elsif q == "no"
          @voter.conVal += 10
          @voter.save
        else
          render :new 
          flash[:notice] = "There was an error handling your quiz. Please correct the missing fields."
        end
      end
        # libVals for each candidate: Trump: 1, Cruz: 15, Rubio: 30, Clinton: 80, Sanders: 99. conVals fill out the rest of the metric to 100.
      if @voter.libVal > 80
      redirect_to candidate_path(id:3)
    elsif @voter.conVal > 85
      redirect_to candidate_path(id:1)
    elsif @voter.libVal > 30 && @voter.conVal > 1
      redirect_to candidate_path(id:2)
    elsif @voter.libVal > 15 && @voter.conVal > 20
      redirect_to candidate_path(id:4)
    elsif @voter.conVal > 70 && @voter.conVal < 99
      redirect_to candidate_path(id:5)
    else 
      redirect_to new_quiz_path
      flash[:alert] = "That didn't work. Try again?"
    end
    end
   end

  def show
   @quiz = Quiz.find(current_voter.id)

  end

 

  private

  def quiz_params
    params.require(:quiz).permit(:voter_id, :answer1, :answer2, :answer3, :answer4, :answer5, :answer6, :answer7, :answer8, :answer9, :answer10)
  end
  
end





# Revisit and revise line 13 (should be @voter)
# Revisit line 14 current_voter.quizzes
# Line 15 shouldn't be quiz.results.save
# Tweak alert info on line 16
# Change redirect on line 18
# Check on line 20
# Revise show action
# Delete destroy action
# Revisit params
# Remove 27

# Quiz model revise the has_manys: only needs to say "belongs to voter"
# Check for attempts controller affected areas
# Remove attempts, questions, and answers table
# Update attributes on quiz table and associate with voter table
#   Each quiz has a voter id? Each voter has a quiz id?
# Update quiz model: Quiz.new(question1....q6:string, answA:boolean, answB:boolean, results: integer, voter_id references)
# Where do we set and store the numerical value related to each boolean checkbox?

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	@voter = Voter.where(email: params[:email]).first
  	if @voter && @voter.authenticate(params[:password])
			session[:voter_id] = @voter.id
			redirect_to '/intro'
		else
			redirect_to login_path
		end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  def new
  	@voter = Voter.new
  end

  def create

  	@voter = Voter.new(voter_params)
      @voter.conVal = 0
      @voter.libVal = 0
  	if @voter.save
      session[:voter_id] = @voter.id
      flash[:notice] = "User signed in successfully."
    	redirect_to '/intro'
 	  else
 		render 'new'
    flash[:notice] = "There was a problem signing you in."
  	end
  end


  def show
  	@voter = Voter.find(params[:id])
  end


  def edit
  	@voter = Voter.find(params[:id])
  end

  def update
  	@voter = Voter.find(params[:id])
  	if @voter.update_attributes(voter_params)

  		redirect_to intro_path
  	else
  		render edit_voter_path
  	end
  end

  def destroy
  	@voter = Voter.find(params[:id])
  	@voter.destroy
    session.clear
  	redirect_to root_path
  end


  private
  def voter_params
  	params.require(:voter).permit(:email, :password, :libVal, :conVal)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/voter_helper.rb
module VoterHelper
end

app/views/candidates/index.html.erb
<h3 class="CoC">Who wants to be a Commander-In-Chief?</h3>

<div class="prezboard">
	
		<% @candidates.each do |c| %>
		<div class="prezPic">
			<%=image_tag c.avatar.url(:medium) %>
		</div>
		<div class="prezName">
			<%=c.fname %>
			<%=c.lname %>
			<p>Who is a:</p><p><%=c.party %></p>
		</div>
		<% end %>
</div>

app/views/candidates/show.html.erb
<div class="candidate">
	<h3>Your best match: <%= @c.fname %> <%= @c.lname %></h3>
	<%= image_tag @c.avatar.url(:medium) %>
	<p><b>Party:</b> <%= @c.party %></p>
	<p><b>Hometown:</b> <%= @c.city %>, <%=@c.state%></p>
</div>

<div class="score">
Your Quiz Score is:
Conservative Percentage:
<%=@v.conVal %>
Liberal Percentage: 
<%=@v.libVal %>
</div>
<!-- button link to the candidate's campaign page -->

app/views/home/intro.html.erb
<!-- <script src= "application.js" text="text/javascript"></script> -->
	
<%= render "layouts/navBar"%>

			
	</div>
	<div class= "polysci">
	<h2>Two Major Parties</h2><p>
	The American Political system currently revolves around two different mindsets: Liberal and Conservative (or left and right, accordingly). The Democratic party is associated with holding mostly left-wing or liberal positions, while the Republican party is associated with holding mostly right wing or conservative positions. There are other positions and parties (The Green party being a famous example), but they are generally outliers with little to no impact on the current political process.
	</p>
	</div>
<!-- <img src="http://www.flagguys.com/img/poldem.gif"> -->
<div class="content">
	<h2>What's a Liberal?</h2>
	<p>
	For a person to be Liberal generally means that they base their worldview and political opinions towards creating the most freedom for the individual, while also protecting the rights that govern individuals' ability to act as they see fit. They see the government as a method of ensuring those freedoms remain intact, enforcing rules to ensure a general equality among all people. 
	</p>
<!-- </div> -->
<!-- <img src="http://www.thenewsburner.com/wp-content/uploads/2012/09/081025_gop_logo.jpg"> -->
<!-- <div class="content"> -->
	<br>
	<h2>What's a Conservative?</h2>
	<p>
	For a person to be Conservative generally means that they base their worldview and political opinions towards maintaining a preestablished order, or returning society to an idea of "the way things were." In American politics, Conservatives tend to see the large, federal government (The White House, the Senate, etc.) as too much of an authority, restricting small groups of people (such as states) from self-governing as they see fit. 
	</p>
</div>

<!-- 	<p>
	As a rule of thumb, Liberalism tends to embrace change, while Conservatives tend to avoid change. Liberals tend to favor raising taxes and using the money gained on government programs, while Conservatives tend to favor lowering taxes and letting the government take a backseat to how money and culture are handled within a country. 
</p>
<p>
	For example, a Liberal view might be to place restrictions on stock traders at Wall Street to prevent them from cheating their clients. A Conservative view might be to let the customers make their own decisions, and stop using Wall Street as customers if they find out they are being cheated, effectively letting the customers regulate the market on their own.
</p> -->
<div class="quiz-text">
	<h5>Now that you get the theory, take our values quiz</h5>
	<div id="log-btn"><%=link_to 'Begin Quiz', new_quiz_path %></div>
</div>

app/views/home/select.html.erb
<!-- DELETE THIS PAGE ON TUES 2/9
 --><h2>Which party do you want to explore?</h2>

<h3>Democratic</h3>
<h3>Republican</h3>
<!-- These two options might be buttons, or a picture of a donkey that you can interact with, whatever... -->

<!-- OR we might not need this page...if there are two links on the issues spine page instead -->

app/views/home/welcome.html.erb
<div class="welcome-wrap">
	<div class="homepage">
		<p>Match with candidates on the issues you care about most.
		</p>
		<%= flash[:alert] if flash[:alert] %>
		<div id="log-btn">
			<%=link_to 'Log In', new_session_path%>
		</div>

		<div id="sign-btn">
			<%= link_to 'Sign up', new_voter_path%>
		</div>
	</div>
</div>

app/views/layouts/_navBar.html.erb
<div class="navBar">
<h3>navBar text with logo here</h3>
<%=link_to "Log Out", logout_path%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VoterApp</title>
  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

	<link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>

</head>
<div id="header">
	<h1 id="logo">Voter</h1>
	<%=link_to "Log Out", logout_path%>
</div>	
</div>
<body>

<%= yield %>
<!-- <footer>
	<ul>
	   <li><a href= "#">About</a></li>
	   <li><a href="#">Contact</a></li>
	   <li><a href="#">FAQ</a></li>
	</ul>
</footer>  -->

</body>
</html>

app/views/quiz/_new.html.erb
<p>testing this page for quizzes. created a partial to display on the intro erb</p>

<%=form_tag quiz_index_path do %>
<%=label_tag :answer1  %>
<%=check_box_tag :answer1%>
<%#=label_tag :answer1  %>
<%=check_box_tag :answer1%>
<%#=label_tag :answer1  %>
<%=check_box_tag :answer1%>
<%=label_tag :answer1  %>
<%=check_box_tag :answer1%>
<%=submit_tag "Submit" %>
<% end %>

app/views/quizzes/create.html.erb
<h1>Quiz#create</h1>
<p>Find me in app/views/quiz/create.html.erb</p>
<!-- REMOVE ME LATER WHEN LOGIC IS COMPLETE! -->

app/views/quizzes/new.html.erb
<div class="quizNav">
	<%= render "layouts/navBar"%>
</div>	
<div class="quiz_instruction">

</div>
<div class="quiz">
	<div id="instr">
		<p>Read each question, think about your view and values, then write <b>"yes" or "no"</b> in the answer field.</p>
		<p><b>Make sure to answer all 10 questions before submitting.</b></p>
	</div>
<%=form_for @quiz do |q|%>
	<div class="ans">
		<p>Should abortion remain legal?</p>
		<%=q.text_field :answer1%>
	</div>
	<div class="ans">
		<p>Should gay marriage remain legal?</p>
		<%=q.text_field :answer2%>
	</div>
	<div class="ans">
		<p>Should college tuition be paid by the government?</p>
		<%=q.text_field :answer3%>
	</div>
	<div class="ans">
		<p>Should health care be provided as a right?</p>
		<%=q.text_field :answer4%>
	</div>
	<div class="ans">
		<p>Should the country have stricter gun control?</p>
		<%=q.text_field :answer5%>
	</div>
	<div class="ans">
		<p>Should the US accept Syrian refugees?</p>
		<%=q.text_field :answer6%>
	</div>
	<div class="ans">
		<p>Should there be a legal path to citizenship for undocumented immigrants?</p>
		<%=q.text_field :answer7%>
	</div>
	<div class="ans">
		<p>Increase the minimum wage?</p>
		<%=q.text_field :answer8%>
	</div>
	<div class="ans">
		<p>Should we separate prayer from schools?</p>
		<%=q.text_field :answer9%>
	</div>
	<div class="ans">
		<p>Should affirmative action remain in place?</p>
		<%=q.text_field :answer10%>
	</div>
	<br>
	<div id="quiz-btn">
		<%=q.submit %>
	</div>
<%end%>

app/views/quizzes/show.html.erb
<!-- SHOW QUIZ MATCH RESULTS HERE -->

app/views/voters/edit.html.erb
<div class="sign-up-form">
	<p>Update your email address in the form below</p>
	<%=form_for @voter do |f|%>	
		<%=f.label :email %>
		<%=f.text_field :email%>
		<%=f.label :password%>
		<%=f.password_field :password%>
		<%=f.submit "Save changes"%> 
	<%end%>
	<br>
	<p>Or, <%= link_to 'Delete', voter_path(@voter.id), method: :delete %> this account </p>
</div>


		

app/views/voters/new.html.erb
<div class="sign-up-form">
<h3>Sign Up</h3>
<%=form_for @voter do |f| %>
  <%=f.label :email %>
  <%=f.text_field :email %>
  <br>
  <%=f.label :password %>
  <%=f.password_field :password %>
  <%=f.submit "Create account"%>
<% end %>

</div>

app/views/voters/show.html.erb
<h1>Voter#show</h1>
<!-- do we need this page? maybe not -->